# Generated by Django 5.1.2 on 2024-10-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BladeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed_blade', 'Fixed Blade'), ('folder', 'Folder'), ('balisong', 'Balisong'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_type', models.CharField(choices=[('blade', 'Blade'), ('handle', 'Handle'), ('hardware', 'Hardware'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Knife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=155)),
                ('bladeTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knifeapi.bladetype')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knives', to=settings.AUTH_USER_MODEL)),
                ('mods', models.ManyToManyField(related_name='knives_with_mods', to='knifeapi.mod')),
            ],
        ),
        migrations.CreateModel(
            name='KnifeMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knifeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knife_mod_associations', to='knifeapi.knife')),
                ('modId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_associations', to='knifeapi.mod')),
            ],
            options={
                'unique_together': {('knifeId', 'modId')},
            },
        ),
    ]
