# Generated by Django 5.1.2 on 2024-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knifeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bladetype',
            name='blade_type',
        ),
        migrations.AddField(
            model_name='bladetype',
            name='type',
            field=models.CharField(choices=[('fixed_blade', 'Fixed Blade'), ('folder', 'Folder'), ('balisong', 'Balisong'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
